export const CATEGORY_MAPPING: Record<string, string[]> = {
  "Mom & Baby": [
    "Diapers & Changing",
    "Baby Milk & Accessories",
    "Baby Food & Tools",
    "Mommy Care",
    "Bathing & Care",
    "Travel & Gear",
    "Baby Healthcare",
    "Toys & Activities",
    "Clothes & Shoes",
    "Sleeping Essentials",
    "Baby & Kids Safety",
  ],
  "Vitamins & Supplements": [
    "Health Conditions",
    "Vitamins",
    "Minerals",
    "Supplements",
    "Herbal Formulas",
    "Kid's Health",
    "Men's Health",
    "Women's Health",
    "Senior's Health",
  ],
  "Treatments": [
    "Antiseptics",
    "Bandages & Wound Care",
    "Pain Relief",
  ],
  "Skin Care": [
    "Cleansers",
    "Moisturizers",
    "Serum",
    "Masks",
    "Sun Care",
    "Foot Care",
    "Skin Tech Tools",
  ],
  "Hair Care": [
    "Shampoo & Conditioner",
    "Hair Nourishment",
    "Hair Styling",
    "Hair Brushes & Accessories",
    "Hair Styling Devices",
    "Hair Coloring",
    "Salon Hair Care",
    "Hair & Scalp Treatment",
    "Professional Hair Care",
  ],
  "Makeup & Lenses": [
    "Face",
    "Eyes",
    "Eyelashes",
    "Lips",
    "Accessories",
    "Makeup Removers",
    "Optical & Lenses",
    "Nails",
  ],
  "Personal Care": [
    "Bath & Body",
    "Oral Care",
    "Feminine Care",
    "Men Care",
    "Deodorants",
    "Household & Hygienic",
    "Hair Removals",
    "Sexual Care",
  ],
  "Home Health Care": [
    "Diabetic Management",
    "Incontinence",
    "Health Monitors",
    "Pain Management",
    "Wheelchairs & Canes",
    "First Aid & Disposables",
    "Face Masks",
    "Fitness & Weight Management",
    "Professional Equipments",
    "Respiratory Equipments",
    "Foot Care",
  ],
};

export const MAIN_CATEGORIES = Object.keys(CATEGORY_MAPPING);
